name: Test
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencias
        run: npm ci
      - name: Run tests
        run: npm test

